import { promises as fs } from 'node:fs'
import path from 'node:path'
import type { ToolSubcategory } from '@/lib/types/tool-subcategory'
import type { Grade } from '@/lib/types/kit'

const ALL_GRADES: Grade[] = [
  'HG',
  'RG',
  'MG',
  'MG-VerKa',
  'PG',
  'PG-Unleashed',
  'EG',
  'SD',
  'SDCS',
  'RE100',
  'FM',
]
const PAINT_GRADES: Grade[] = ['MG', 'MG-VerKa', 'PG', 'PG-Unleashed', 'RG']

const SUBCATEGORIES: ToolSubcategory[] = [
  // ── CUTTING ─────────────────────────────────────────────────
  {
    id: 'single-blade-nipper',
    category: 'cutting',
    name_zh: '单刃水口钳',
    name_en: 'Single-Blade Nipper',
    what_it_is: '一刃锋利、一刃为平砧的剪钳。社区俗称"小红钳"或"神之手钳"。',
    why_you_need_it: '剪水口（零件与板架的连接点）时水口痕几乎不留白——这是双刃钳无法做到的。',
    when_to_use: '拼装任何 grade 的所有零件取件，是和模型接触最多的工具。',
    vs_alternatives: 'vs 双刃钳——双刃挤断会留白；vs 指甲剪/手术剪——压根没法用。',
    urgency: 'essential',
    pitfalls: [
      '单刃刃薄易崩，绝对不要剪铜线/钢丝/流道根部（流道根部用双刃钳）',
      '不用时套钳套，平时不要随手放桌上',
      '国产小蓝钳是社区公认的智商税，请避免',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 12, y: 25 },
    icon: 'nipper-single',
    popular_products: [],
  },
  {
    id: 'double-blade-nipper',
    category: 'cutting',
    name_zh: '双刃普通钳',
    name_en: 'Double-Blade Nipper',
    what_it_is: '两刃都开锋的剪钳。代表是田宫薄刃钳（74035）。',
    why_you_need_it: '作为副钳处理粗剪流道、铜棒打桩、修剪不需要精度的废件——保护单刃钳不崩刃。',
    when_to_use: '剪流道根部的"第一刀"、剪铜棒、剪不需要不留白的废件。',
    vs_alternatives: 'vs 单刃钳——双刃耐造但留白；vs 流道钳——流道钳粗大不灵活。',
    urgency: 'recommended',
    pitfalls: [
      '不要拿双刃钳去精剪水口——会发白',
      '田宫金牌剪是经典款但常断货，可考虑国产 DSPIAE 替代',
    ],
    recommended_for_grades: ['HG', 'RG', 'MG', 'PG'],
    workshop_zone: 'pegboard',
    workshop_position: { x: 24, y: 25 },
    icon: 'nipper-double',
    popular_products: [],
  },
  {
    id: 'hobby-knife',
    category: 'cutting',
    name_zh: '笔刀',
    name_en: 'Hobby Knife',
    what_it_is: '可换刃的精密小刀，像手术刀。',
    why_you_need_it: '剪钳剪完留下的残留水口需要笔刀贴肉削平；切水贴；切胶带做遮盖。',
    when_to_use: '每次剪件后的"第二步处理"。',
    vs_alternatives: 'vs 美工刀——美工刀刃片有晃动、控制不精；vs 直接打磨——笔刀比砂纸快十倍。',
    urgency: 'essential',
    pitfalls: [
      '会割手！强烈建议配指套 / 切割垫',
      '刀片钝了立刻换，钝刀比利刀更危险（容易打滑）',
      'OLFA 笔刀是社区公认顶级，田宫笔刀实际是 OLFA 代工',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 36, y: 25 },
    icon: 'knife',
    popular_products: [],
  },
  {
    id: 'sprue-cutter',
    category: 'cutting',
    name_zh: '流道钳 / 大力钳',
    name_en: 'Sprue Cutter',
    what_it_is: '粗壮的剪钳，专门剪粗流道。',
    why_you_need_it: 'PG 级别流道很粗，拿薄刃钳硬剪会崩。',
    when_to_use: '仅 PG / PG-Unleashed / 大型 MG 改造时。',
    vs_alternatives: 'vs 双刃钳——双刃钳剪粗流道也会崩。',
    urgency: 'advanced',
    pitfalls: ['留白严重，不能拿来剪零件'],
    recommended_for_grades: ['PG', 'PG-Unleashed'],
    workshop_zone: 'pegboard',
    workshop_position: { x: 48, y: 25 },
    icon: 'nipper-sprue',
    popular_products: [],
  },

  // ── SANDING ─────────────────────────────────────────────────
  {
    id: 'sanding-stick',
    category: 'sanding',
    name_zh: '打磨棒 / 打磨板',
    name_en: 'Sanding Stick',
    what_it_is: '一块硬底板，配砂纸贴上去使用。',
    why_you_need_it: '直接拿砂纸打磨会把零件磨成圆弧——失去原本的锐利棱角；硬底板能保平整。',
    when_to_use: '素组党可选；想做细节的"洗件"前必备。',
    vs_alternatives: 'vs 海绵砂纸——海绵适合曲面、硬板适合平面。',
    urgency: 'recommended',
    pitfalls: [
      '不要买软底打磨棒（美甲那种），会把零件磨肉',
      '硬底优先：碳纤维、金属、塑料板。RAY 模师傅的打磨板是社区共识首选',
    ],
    recommended_for_grades: ['HG', 'RG', 'MG', 'PG', 'RE100', 'FM'],
    workshop_zone: 'pegboard',
    workshop_position: { x: 60, y: 25 },
    icon: 'sandstick',
    popular_products: [],
  },
  {
    id: 'sandpaper',
    category: 'sanding',
    name_zh: '砂纸',
    name_en: 'Sandpaper',
    what_it_is: '研磨纸，按"目数"区分粗细。数字越大越细。',
    why_you_need_it: '磨除水口痕、合模线、表面瑕疵。',
    when_to_use: '素组细节党；涂装前必做。',
    vs_alternatives: 'vs 海绵砂纸——硬砂纸平面、海绵砂纸曲面。',
    urgency: 'recommended',
    pitfalls: [
      '必须从小目数到大目数渐进：通常 600 → 800 → 1000 → 1500 → 2000',
      '推荐水砂纸（沾水使用），可以减少粉尘和砂纸损耗',
      '打磨后戴口罩或用湿海绵收尘——粉尘有害健康',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 72, y: 25 },
    icon: 'sandstick',
    popular_products: [],
  },
  {
    id: 'sponge-file',
    category: 'sanding',
    name_zh: '海绵砂纸',
    name_en: 'Sponge File',
    what_it_is: '软底海绵 + 砂面。',
    why_you_need_it: '曲面、圆角、内凹——硬砂纸打不到的地方。',
    when_to_use: '处理零件曲面、抛光阶段。',
    vs_alternatives: 'vs 砂纸——硬平面用砂纸，曲面/抛光用海绵。',
    urgency: 'advanced',
    pitfalls: ['海绵砂纸不要用来打平面，会把平面打圆'],
    recommended_for_grades: ['MG', 'PG', 'RG'],
    workshop_zone: 'pegboard',
    workshop_position: { x: 84, y: 25 },
    icon: 'sandstick',
    popular_products: [],
  },
  {
    id: 'file',
    category: 'sanding',
    name_zh: '锉刀',
    name_en: 'File',
    what_it_is: '金属磨锉条。',
    why_you_need_it: '重度修整（合模线、改件、补件）。',
    when_to_use: '改造党 / 整改老模型。',
    vs_alternatives: 'vs 砂纸——锉刀力度大但容易过头；砂纸细但慢。',
    urgency: 'advanced',
    pitfalls: ['手抖直接磨穿零件'],
    recommended_for_grades: ['MG', 'PG', 'RG', 'RE100', 'FM'],
    workshop_zone: 'workbench',
    workshop_position: { x: 22, y: 35 },
    icon: 'file',
    popular_products: [],
  },
  {
    id: 'polishing-compound',
    category: 'sanding',
    name_zh: '抛光膏',
    name_en: 'Polishing Compound',
    what_it_is: '膏状研磨剂，配棉布抛光。',
    why_you_need_it: '做镜面效果（透明件、金属漆面）。',
    when_to_use: '完成细节阶段，做高光泽收尾。',
    urgency: 'advanced',
    pitfalls: ['过度抛光反而会损伤漆面'],
    recommended_for_grades: ['MG', 'PG'],
    workshop_zone: 'workbench',
    workshop_position: { x: 32, y: 35 },
    icon: 'polishing',
    popular_products: [],
  },

  // ── PAINTING ───────────────────────────────────────────────
  {
    id: 'detail-brush',
    category: 'painting',
    name_zh: '笔涂笔 / 面相笔',
    name_en: 'Detail Brush',
    what_it_is: '细毛笔。"面相笔"特指最细的一档（5/0、10/0 号）。',
    why_you_need_it: '补色、点缀、写字、笔涂细节。',
    when_to_use: 'HG 的局部补色（动力管、传感器）；任何 grade 的眼睛细节。',
    vs_alternatives: 'vs 马克笔——笔涂可控、马克笔粗但快。',
    urgency: 'recommended',
    pitfalls: [
      '用完立刻洗，硝基/珐琅漆干硬就毁笔',
      '田宫 HF 系列、郡士 PRO 系列、温莎牛顿都是社区共识好货',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'workbench',
    workshop_position: { x: 42, y: 35 },
    icon: 'paintbrush',
    popular_products: [],
  },
  {
    id: 'brush-paint',
    category: 'painting',
    name_zh: '笔涂漆',
    name_en: 'Brush-On Paint',
    what_it_is: '用刷子能上的漆。社区主流是水性漆（郡士 AQUEOUS、田宫水性）和珐琅漆（田宫 X / XF 系列）。',
    why_you_need_it: '补色 / 笔涂的颜料源头。',
    when_to_use: '所有需要上色的场景。',
    vs_alternatives: '水性漆笔涂友好但覆盖力一般；硝基漆覆盖强但不适合笔涂；珐琅漆缓干笔涂神器但溶剂可能伤塑料。',
    urgency: 'recommended',
    pitfalls: [
      '不要混用不同体系的漆（水/油/珐琅会互相反应）',
      '珐琅漆稀释剂不要直接接触塑料件',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'cabinet-left',
    workshop_position: { x: 8, y: 50 },
    icon: 'palette',
    popular_products: [],
  },
  {
    id: 'airbrush',
    category: 'painting',
    name_zh: '喷笔',
    name_en: 'Airbrush',
    what_it_is: '精密喷涂工具，靠气压把漆雾化。',
    why_you_need_it: '大面积均匀上色、阴影、渐变、金属漆。',
    when_to_use: '进入正式喷涂阶段后。',
    vs_alternatives: '双动喷笔（push 出气、pull 出漆）—— 主流，灵活；单动喷笔气漆联动，简单但不灵活。',
    urgency: 'advanced',
    pitfalls: [
      '必备配套：气泵 + 喷漆台 + 防毒面具（缺一不可）',
      '用完必须清洗，硝基漆不洗笔会报废',
      '0.3mm 口径是新手最佳——0.2mm 太细易堵、0.5mm 太粗',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'cabinet-right',
    workshop_position: { x: 92, y: 22 },
    icon: 'airbrush',
    popular_products: [],
  },
  {
    id: 'compressor',
    category: 'painting',
    name_zh: '气泵',
    name_en: 'Air Compressor',
    what_it_is: '给喷笔提供稳定气压的电动泵。',
    why_you_need_it: '喷笔的命根子，没气泵喷笔就是装饰。',
    when_to_use: '和喷笔一套。',
    vs_alternatives: '模型泵静音小巧；工业泵声音大但便宜耐用；便携泵气压不稳。',
    urgency: 'advanced',
    pitfalls: [
      '楼房住户优先模型泵——工业泵噪音扰邻',
      '必须有储气罐，否则气压抖动严重',
      '长时间使用气泵会发热，间歇休息或加风扇',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'cabinet-right',
    workshop_position: { x: 92, y: 55 },
    icon: 'compressor',
    popular_products: [],
  },
  {
    id: 'spray-booth',
    category: 'painting',
    name_zh: '喷漆台 / 喷漆箱',
    name_en: 'Spray Booth',
    what_it_is: '带排风扇的小箱子，把油漆雾气抽出室外。',
    why_you_need_it: '安全！油漆雾化吸入肺会要命；同时减少落灰。',
    when_to_use: '所有喷涂作业。',
    vs_alternatives: 'vs 直接在阳台喷——阳台无法挡灰，邻居投诉。',
    urgency: 'advanced',
    pitfalls: [
      '排风必须接到室外或开窗，不能内循环',
      '入门款：迪斯派 / 模研能者（300-1000）',
      '高端：模研能者水帘款（带水雾过滤，2000+）',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'cabinet-left',
    workshop_position: { x: 8, y: 22 },
    icon: 'spray-booth',
    popular_products: [],
  },
  {
    id: 'spray-paint',
    category: 'painting',
    name_zh: '喷涂漆',
    name_en: 'Spray-Grade Paint',
    what_it_is: '硝基漆为主，主流品牌：郡士 Mr.Color、盖亚 GaiaNotes、田宫硝基、狐火御调漆、喵匠预调漆。',
    why_you_need_it: '喷笔用漆的源头。',
    when_to_use: '喷涂阶段。',
    vs_alternatives: '硝基/水性/珐琅 — 硝基覆盖力最强、水性最环保、珐琅缓干。',
    urgency: 'advanced',
    pitfalls: [
      '必须用对应的稀释剂——硝基用硝基溶剂、水性用水性溶剂',
      '金属漆要用专用溶剂稀释',
      '油漆有毒，必须搭配防毒面具',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'cabinet-left',
    workshop_position: { x: 8, y: 75 },
    icon: 'spray-can',
    popular_products: [],
  },
  {
    id: 'surfacer',
    category: 'painting',
    name_zh: '水补土',
    name_en: 'Surfacer / Primer',
    what_it_is: '底漆，喷在塑料件表面给后续漆面"打底"。',
    why_you_need_it: '让面漆附着力更强、颜色更准、暴露细节问题。',
    when_to_use: '喷涂前；改件后填缝。',
    vs_alternatives: '水补土兼具底漆和填补功能。',
    urgency: 'advanced',
    pitfalls: [
      '灰色（500/1000/1200）最常用，黑色用于深色面漆',
      '喷得太厚会糊住细节',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'cabinet-left',
    workshop_position: { x: 8, y: 88 },
    icon: 'spray-can',
    popular_products: [],
  },

  // ── FINISHING ───────────────────────────────────────────────
  {
    id: 'panel-liner',
    category: 'finishing',
    name_zh: '渗线液',
    name_en: 'Panel Liner',
    what_it_is: '低粘度颜料，能自动渗入零件凹槽。',
    why_you_need_it: '让模型刻线/缝隙变得立体感强烈——这是素组到"看着像样"的最大单一变量。',
    when_to_use: '拼装前或拼装后均可。',
    vs_alternatives: 'vs 勾线笔——勾线笔需要手稳画线；渗线液点一下自动流。',
    urgency: 'recommended',
    pitfalls: [
      '饼干化风险：田宫珐琅漆基底的渗线液有概率让塑料变脆。不放心可先喷一层光油保护',
      '颜色：黑色（最常用）、灰色（白色机体）、棕色（暖色机体）',
      '田宫 87131-87133、郡士 GM02-04 是社区主流',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 12, y: 50 },
    icon: 'pen-line',
    popular_products: [],
  },
  {
    id: 'panel-liner-pen',
    category: 'finishing',
    name_zh: '渗线笔',
    name_en: 'Panel Liner Pen',
    what_it_is: '渗线液的笔形版本，按压自动出墨。',
    why_you_need_it: '比液体渗线液更可控，新手更友好。',
    when_to_use: '替代或补充渗线液。',
    vs_alternatives: 'vs 渗线液——笔形便携、液体覆盖更好。',
    urgency: 'recommended',
    pitfalls: ['用前充分摇晃，否则颜色不均'],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 24, y: 50 },
    icon: 'pen-line',
    popular_products: [],
  },
  {
    id: 'decals-and-setter',
    category: 'finishing',
    name_zh: '水贴 / 软化剂',
    name_en: 'Decals & Setter',
    what_it_is: '印有图案的薄膜贴纸（水贴沾水后揭下贴；胶贴直接撕贴；干贴/刮贴摩擦转印）。',
    why_you_need_it: '模型自带细节贴纸，万代有的给水贴有的给胶贴。',
    when_to_use: '模型完成度的"最后一公里"。',
    vs_alternatives: '水贴最薄但难贴；胶贴最厚但简单；刮贴中庸。',
    urgency: 'essential',
    pitfalls: [
      '水贴需要软化剂配合，否则贴不平、不服帖曲面',
      '田宫 87193 / 郡士 Mr.Mark Setter 是经典软化剂',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 36, y: 50 },
    icon: 'sticker',
    popular_products: [],
  },
  {
    id: 'topcoat',
    category: 'finishing',
    name_zh: '消光 / 光油 / 半消光',
    name_en: 'Topcoat',
    what_it_is: '透明保护漆，喷或涂在最外层。',
    why_you_need_it: '消光去掉塑料光泽（瞬间从"玩具"变"模型"）；光油增加光泽适合金属漆面；半消光折中。',
    when_to_use: '所有完成步骤之后的最后一道。',
    vs_alternatives: '消光最常见，光油适合展示级，半消光最稳。',
    urgency: 'recommended',
    pitfalls: [
      '罐装喷漆新手友好（无需喷笔），但味道大需通风',
      '喷消光后不能再贴水贴——表面会变粗糙',
      '水性消光（如郡士新水性）味道较小，适合家用',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'cabinet-left',
    workshop_position: { x: 8, y: 35 },
    icon: 'spray-can',
    popular_products: [],
  },
  {
    id: 'weathering',
    category: 'finishing',
    name_zh: '旧化粉 / 旧化液',
    name_en: 'Weathering Pigment',
    what_it_is: '模拟战损、生锈、灰尘的颜料。',
    why_you_need_it: '增加机体真实感（高达圈称为"做铁血风"或"军模化"）。',
    when_to_use: '进阶完成后的风格化处理。',
    urgency: 'advanced',
    pitfalls: ['很容易做过头变难看，少量多次'],
    recommended_for_grades: ['HG', 'MG', 'RE100', 'FM'],
    workshop_zone: 'cabinet-left',
    workshop_position: { x: 8, y: 62 },
    icon: 'droplet',
    popular_products: [],
  },

  // ── ASSIST ─────────────────────────────────────────────────
  {
    id: 'tweezers',
    category: 'assist',
    name_zh: '镊子',
    name_en: 'Tweezers',
    what_it_is: '精密夹取工具。',
    why_you_need_it: '贴水贴/胶贴的唯一选择——手指太粗。',
    when_to_use: '贴贴纸、夹小零件。',
    vs_alternatives: 'vs 手指——手指会留指纹和油渍。',
    urgency: 'essential',
    pitfalls: [
      '直头适合大部分场景；弯头适合特殊角度',
      '防静电款（黑色）更安全，不易弹飞贴纸',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 48, y: 50 },
    icon: 'tweezers',
    popular_products: [],
  },
  {
    id: 'clip-stick',
    category: 'assist',
    name_zh: '持件夹',
    name_en: 'Alligator Clips on Stick',
    what_it_is: '竹签 + 夹子，用来夹住零件喷涂。',
    why_you_need_it: '喷涂时不能手拿零件——会留指纹/挡漆。',
    when_to_use: '所有喷涂场景。',
    urgency: 'recommended',
    pitfalls: [
      '数量要够多（一台 MG 喷涂同时需要 30+ 个夹）',
      '夹子有粗细，搭配使用',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'workbench',
    workshop_position: { x: 52, y: 35 },
    icon: 'clip-stick',
    popular_products: [],
  },
  {
    id: 'palette',
    category: 'assist',
    name_zh: '调色皿 / 调色盘',
    name_en: 'Palette',
    what_it_is: '装漆调色用的小皿。',
    why_you_need_it: '调色 / 漆从瓶里倒出来用更可控。',
    when_to_use: '所有需要调漆的场景。',
    urgency: 'recommended',
    pitfalls: ['硝基漆会腐蚀塑料调色盘——优先用陶瓷或不锈钢'],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'workbench',
    workshop_position: { x: 62, y: 35 },
    icon: 'palette',
    popular_products: [],
  },
  {
    id: 'turntable',
    category: 'assist',
    name_zh: '模型台 / 转台',
    name_en: 'Turntable',
    what_it_is: '旋转底座，放零件方便观察。',
    why_you_need_it: '喷涂时旋转看死角；展示时 360 度看。',
    when_to_use: '展示或喷涂时。',
    urgency: 'advanced',
    pitfalls: [],
    recommended_for_grades: ['MG', 'PG', 'RE100'],
    workshop_zone: 'workbench',
    workshop_position: { x: 50, y: 78 },
    icon: 'disc',
    popular_products: [],
  },
  {
    id: 'glue',
    category: 'assist',
    name_zh: '胶水',
    name_en: 'Model Cement / Glue',
    what_it_is: '粘接剂。田宫绿盖溜缝胶最常用。',
    why_you_need_it: '万代模型理论上不需要胶（snap-fit），但改件、固定关节需要。',
    when_to_use: '改件 / 旧零件松动 / 修补。',
    vs_alternatives: '502 通用强力但留白；田宫绿盖流动性强用于无缝处理；田宫白盖粘稠固定零件；郡士透明接着剂粘透明件不留雾。',
    urgency: 'advanced',
    pitfalls: ['502 在塑料表面会留白雾，谨慎用'],
    recommended_for_grades: ['MG', 'PG', 'RE100', 'FM'],
    workshop_zone: 'pegboard',
    workshop_position: { x: 60, y: 50 },
    icon: 'flask',
    popular_products: [],
  },
  {
    id: 'part-separator',
    category: 'assist',
    name_zh: '开模器 / 分件器',
    name_en: 'Part Separator',
    what_it_is: '薄片金属/塑料，撬开拼错的零件。',
    why_you_need_it: '万代零件一旦扣紧，徒手拆容易断。',
    when_to_use: '拼错时救急。',
    vs_alternatives: 'vs 笔刀——熟练后笔刀可代替，但新手安全起见用专用工具。',
    urgency: 'recommended',
    pitfalls: ['金属开模器力度大易刮伤；塑料款易断'],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'pegboard',
    workshop_position: { x: 72, y: 50 },
    icon: 'part-separator',
    popular_products: [],
  },

  // ── WORKSPACE ──────────────────────────────────────────────
  {
    id: 'cutting-mat',
    category: 'workspace',
    name_zh: '切割垫',
    name_en: 'Cutting Mat',
    what_it_is: '自愈合塑料垫板。',
    why_you_need_it: '保护桌面 + 保护笔刀刀刃 + 标尺辅助。',
    when_to_use: '所有工作时铺桌面上。',
    urgency: 'essential',
    pitfalls: ['A4 太小、A2 太大，A3 是黄金尺寸'],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'workbench',
    workshop_position: { x: 50, y: 95 },
    icon: 'square',
    popular_products: [],
  },
  {
    id: 'parts-organizer',
    category: 'workspace',
    name_zh: '零件分装盒',
    name_en: 'Parts Organizer',
    what_it_is: '多格塑料盒。',
    why_you_need_it: '板件剪下后按部位分类，避免找件浪费时间。',
    when_to_use: 'MG/PG 这种零件多的场景。',
    urgency: 'recommended',
    pitfalls: [],
    recommended_for_grades: ['MG', 'PG', 'PG-Unleashed'],
    workshop_zone: 'cabinet-right',
    workshop_position: { x: 92, y: 88 },
    icon: 'package',
    popular_products: [],
  },
  {
    id: 'desk-light',
    category: 'workspace',
    name_zh: '桌面照明',
    name_en: 'Desk Light',
    what_it_is: '可调亮度色温的台灯。',
    why_you_need_it: '暗光下做模型 = 自残。',
    when_to_use: '所有工作时。',
    urgency: 'recommended',
    pitfalls: [
      '优先显色指数 Ra > 90 的灯（颜色判断准）',
      '5000K 中性光是模型环境黄金色温',
    ],
    recommended_for_grades: ALL_GRADES,
    workshop_zone: 'workbench',
    workshop_position: { x: 80, y: 35 },
    icon: 'lamp',
    popular_products: [],
  },
  {
    id: 'respirator',
    category: 'workspace',
    name_zh: '防毒面具',
    name_en: 'Respirator',
    what_it_is: '带活性炭滤芯的口罩。',
    why_you_need_it: '硝基漆有强毒性，吸入伤肝肾。',
    when_to_use: '所有喷涂作业。',
    urgency: 'essential',
    pitfalls: [
      '普通医用口罩没用——挡飞沫不挡有机蒸汽',
      '推荐 3M 6200 或 7502 半面罩 + 6001 有机滤芯',
    ],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'cabinet-right',
    workshop_position: { x: 92, y: 38 },
    icon: 'respirator',
    popular_products: [],
  },
  {
    id: 'dust-blower',
    category: 'workspace',
    name_zh: '吹尘球 / 静电刷',
    name_en: 'Dust Blower',
    what_it_is: '吹气球或抗静电毛刷。',
    why_you_need_it: '喷涂前除尘——零件上一粒灰会让漆面毁了。',
    when_to_use: '喷涂前；展示前。',
    urgency: 'advanced',
    pitfalls: [],
    recommended_for_grades: PAINT_GRADES,
    workshop_zone: 'workbench',
    workshop_position: { x: 70, y: 35 },
    icon: 'wind',
    popular_products: [],
  },
]

async function main() {
  // Validate uniqueness of ids and integrity of references
  const ids = new Set<string>()
  const dups: string[] = []
  for (const sc of SUBCATEGORIES) {
    if (ids.has(sc.id)) dups.push(sc.id)
    ids.add(sc.id)
  }
  if (dups.length) {
    throw new Error(`Duplicate ids: ${dups.join(', ')}`)
  }

  const out = path.resolve('data', 'tool-subcategories.json')
  await fs.writeFile(
    out,
    JSON.stringify(
      { version: 1, count: SUBCATEGORIES.length, items: SUBCATEGORIES },
      null,
      2,
    ) + '\n',
    'utf-8',
  )

  console.log(`Wrote ${SUBCATEGORIES.length} tool subcategories to ${out}`)
  const byZone = SUBCATEGORIES.reduce<Record<string, number>>((acc, sc) => {
    acc[sc.workshop_zone] = (acc[sc.workshop_zone] ?? 0) + 1
    return acc
  }, {})
  console.log('By workshop zone:', byZone)
  const byUrgency = SUBCATEGORIES.reduce<Record<string, number>>((acc, sc) => {
    acc[sc.urgency] = (acc[sc.urgency] ?? 0) + 1
    return acc
  }, {})
  console.log('By urgency:', byUrgency)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
