import type { Work } from '@/lib/types/work'

export const WORKS_SEED: Record<string, Work> = {
  'Mobile Suit Gundam': {
    id: 'msg-0079',
    title_zh: '机动战士高达',
    title_jp: '機動戦士ガンダム',
    era: 'UC',
    year_aired: 1979,
  },
  'Mobile Suit Gundam: The Origin': {
    id: 'msg-the-origin',
    title_zh: '机动战士高达 THE ORIGIN',
    title_jp: '機動戦士ガンダム THE ORIGIN',
    era: 'UC',
    year_aired: 2015,
  },
  'Mobile Suit Zeta Gundam': {
    id: 'msz',
    title_zh: '机动战士Z高达',
    title_jp: '機動戦士Ζガンダム',
    era: 'UC',
    year_aired: 1985,
  },
  'Mobile Suit Gundam ZZ': {
    id: 'msgzz',
    title_zh: '机动战士ZZ高达',
    title_jp: '機動戦士ガンダムΖΖ',
    era: 'UC',
    year_aired: 1986,
  },
  "Mobile Suit Gundam: Char's Counterattack": {
    id: 'cca',
    title_zh: '机动战士高达 逆袭的夏亚',
    title_jp: '機動戦士ガンダム 逆襲のシャア',
    era: 'UC',
    year_aired: 1988,
  },
  'Mobile Suit Gundam Unicorn': {
    id: 'gundam-uc',
    title_zh: '机动战士高达UC',
    title_jp: '機動戦士ガンダムUC',
    era: 'UC',
    year_aired: 2010,
  },
  "Mobile Suit Gundam: Hathaway's Flash": {
    id: 'hathaway',
    title_zh: '机动战士高达 闪光的哈萨维',
    title_jp: '機動戦士ガンダム 閃光のハサウェイ',
    era: 'UC',
    year_aired: 2021,
  },
  'Mobile Suit Gundam Narrative': {
    id: 'narrative',
    title_zh: '机动战士高达NT',
    title_jp: '機動戦士ガンダムNT',
    era: 'UC',
    year_aired: 2018,
  },
  'Mobile Suit Gundam SEED': {
    id: 'seed',
    title_zh: '机动战士高达SEED',
    title_jp: '機動戦士ガンダムSEED',
    era: 'CE',
    year_aired: 2002,
  },
  'Mobile Suit Gundam SEED Destiny': {
    id: 'seed-destiny',
    title_zh: '机动战士高达SEED DESTINY',
    title_jp: '機動戦士ガンダムSEED DESTINY',
    era: 'CE',
    year_aired: 2004,
  },
  'Mobile Suit Gundam SEED Freedom': {
    id: 'seed-freedom',
    title_zh: '机动战士高达SEED FREEDOM',
    title_jp: '機動戦士ガンダムSEED FREEDOM',
    era: 'CE',
    year_aired: 2024,
  },
  'Mobile Suit Gundam 00': {
    id: 'gundam-00',
    title_zh: '机动战士高达00',
    title_jp: '機動戦士ガンダム00',
    era: 'AD',
    year_aired: 2007,
  },
  'Mobile Suit Gundam Wing': {
    id: 'gundam-w',
    title_zh: '新机动战记高达W',
    title_jp: '新機動戦記ガンダムW',
    era: 'AC',
    year_aired: 1995,
  },
  'After War Gundam X': {
    id: 'gundam-x',
    title_zh: '机动新世纪高达X',
    title_jp: '機動新世紀ガンダムX',
    era: 'AW',
    year_aired: 1996,
  },
  'Mobile Fighter G Gundam': {
    id: 'g-gundam',
    title_zh: '机动武斗传G高达',
    title_jp: '機動武闘伝Gガンダム',
    era: 'FC',
    year_aired: 1994,
  },
  'Mobile Suit Gundam: Iron-Blooded Orphans': {
    id: 'ibo',
    title_zh: '机动战士高达 铁血的奥尔芬斯',
    title_jp: '機動戦士ガンダム 鉄血のオルフェンズ',
    era: 'PD',
    year_aired: 2015,
  },
  'Mobile Suit Gundam: The Witch from Mercury': {
    id: 'witch-from-mercury',
    title_zh: '机动战士高达 水星的魔女',
    title_jp: '機動戦士ガンダム 水星の魔女',
    era: 'AS',
    year_aired: 2022,
  },
  'Mobile Suit Gundam: Reconguista in G': {
    id: 'g-reco',
    title_zh: '高达 G之复国运动',
    title_jp: 'ガンダム Gのレコンギスタ',
    era: 'RC',
    year_aired: 2014,
  },

  // ── 03B 追加 ──────────────────────────────────────────────────────
  'Mobile Suit Gundam 0083: Stardust Memory': {
    id: 'gundam-0083',
    title_zh: '机动战士高达0083 星尘的回忆',
    title_jp: '機動戦士ガンダム0083 STARDUST MEMORY',
    era: 'UC',
    year_aired: 1991,
  },
  'Mobile Suit Gundam: The 08th MS Team': {
    id: 'gundam-08ms',
    title_zh: '机动战士高达 第08MS小队',
    title_jp: '機動戦士ガンダム 第08MS小隊',
    era: 'UC',
    year_aired: 1996,
  },
  'Mobile Suit Crossbone Gundam': {
    id: 'crossbone',
    title_zh: '机动战士交叉骨高达',
    title_jp: '機動戦士クロスボーン・ガンダム',
    era: 'UC',
    year_aired: 1994,
  },
  "Mobile Suit Gundam: Char's Counterattack - Beltorchika's Children": {
    id: 'cca-bc',
    title_zh: '逆袭的夏亚 贝托蒂嘉的子供',
    title_jp: '逆襲のシャア ベルトーチカ・チルドレン',
    era: 'UC',
    year_aired: 1988,
  },
  'Mobile Suit Variation': {
    id: 'msv',
    title_zh: 'MSV',
    title_jp: 'MOBILE SUIT VARIATION',
    era: 'UC',
    year_aired: 1983,
  },
  'Mobile Suit Variations': {
    id: 'msv',
    title_zh: 'MSV',
    title_jp: 'MOBILE SUIT VARIATION',
    era: 'UC',
    year_aired: 1983,
  },
  'Mobile Suit Gundam Side Story: The Blue Destiny': {
    id: 'blue-destiny',
    title_zh: '机动战士高达外传 蓝色命运',
    title_jp: '機動戦士ガンダム外伝 ブルー・デスティニー',
    era: 'UC',
    year_aired: 1996,
  },
  'Mobile Suit Gundam Thunderbolt': {
    id: 'thunderbolt',
    title_zh: '机动战士高达 雷霆宙域战线',
    title_jp: '機動戦士ガンダム サンダーボルト',
    era: 'UC',
    year_aired: 2015,
  },
  "Mobile Suit Gundam: Cucuruz Doan's Island": {
    id: 'cucuruz-doan',
    title_zh: '机动战士高达 库库鲁斯·杜安之岛',
    title_jp: '機動戦士ガンダム ククルス・ドアンの島',
    era: 'UC',
    year_aired: 2022,
  },
  'Mobile Suit Gundam F91': {
    id: 'gundam-f91',
    title_zh: '机动战士高达F91',
    title_jp: '機動戦士ガンダムF91',
    era: 'UC',
    year_aired: 1991,
  },
  'Mobile Suit Victory Gundam': {
    id: 'v-gundam',
    title_zh: '机动战士V高达',
    title_jp: '機動戦士Vガンダム',
    era: 'UC',
    year_aired: 1993,
  },
  'Turn A Gundam': {
    id: 'turn-a',
    title_zh: '∀高达',
    title_jp: '∀ガンダム',
    era: 'CC',
    year_aired: 1999,
  },
  'New Mobile Report Gundam Wing': {
    id: 'gundam-w',
    title_zh: '新机动战记高达W',
    title_jp: '新機動戦記ガンダムW',
    era: 'AC',
    year_aired: 1995,
  },
  'New Mobile Report Gundam Wing: Endless Waltz': {
    id: 'gundam-w-ew',
    title_zh: '新机动战记高达W Endless Waltz',
    title_jp: '新機動戦記ガンダムW Endless Waltz',
    era: 'AC',
    year_aired: 1997,
  },
  'New Mobile Report Gundam Wing Endless Waltz: The Glory of Losers': {
    id: 'gundam-w-glory',
    title_zh: '新机动战记高达W 败者们的荣光',
    title_jp: '新機動戦記ガンダムW 敗者たちの栄光',
    era: 'AC',
    year_aired: 2010,
  },
  'Mobile Suit Gundam Wing Endless Waltz: Glory of the Losers': {
    id: 'gundam-w-glory',
    title_zh: '新机动战记高达W 败者们的荣光',
    title_jp: '新機動戦記ガンダムW 敗者たちの栄光',
    era: 'AC',
    year_aired: 2010,
  },
  'Mobile Suit Gundam SEED Astray': {
    id: 'seed-astray',
    title_zh: '机动战士高达SEED ASTRAY',
    title_jp: '機動戦士ガンダムSEED ASTRAY',
    era: 'CE',
    year_aired: 2002,
  },
  'Mobile Suit Gundam SEED MSV': {
    id: 'seed-msv',
    title_zh: '机动战士高达SEED MSV',
    title_jp: '機動戦士ガンダムSEED MSV',
    era: 'CE',
    year_aired: 2003,
  },
  'Mobile Suit Gundam 00 The Movie -A wakening of the Trailblazer-': {
    id: 'gundam-00',
    title_zh: '机动战士高达00',
    title_jp: '機動戦士ガンダム00',
    era: 'AD',
    year_aired: 2007,
  },
  'Mobile Suit Gundam AGE': {
    id: 'gundam-age',
    title_zh: '机动战士高达AGE',
    title_jp: '機動戦士ガンダムAGE',
    era: 'AG',
    year_aired: 2011,
  },
  'Gundam Reconguista in G': {
    id: 'g-reco',
    title_zh: '高达 G之复国运动',
    title_jp: 'ガンダム Gのレコンギスタ',
    era: 'RC',
    year_aired: 2014,
  },
  'Mobile Suit Gundam: Iron-Blooded Orphans Urdr-Hunt': {
    id: 'ibo-urdr',
    title_zh: '机动战士高达 铁血的奥尔芬斯 月钢',
    title_jp: '機動戦士ガンダム 鉄血のオルフェンズ 月鋼',
    era: 'PD',
    year_aired: 2022,
  },
  'Gundam Build Fighters': {
    id: 'build-fighters',
    title_zh: '高达创战者',
    title_jp: 'ガンダムビルドファイターズ',
    era: 'BF',
    year_aired: 2013,
  },
  'Gundam Build Fighters Try': {
    id: 'build-fighters-try',
    title_zh: '高达创战者TRY',
    title_jp: 'ガンダムビルドファイターズトライ',
    era: 'BF',
    year_aired: 2014,
  },
  'Gundam Build Divers': {
    id: 'build-divers',
    title_zh: '高达创战潜者',
    title_jp: 'ガンダムビルドダイバーズ',
    era: 'BF',
    year_aired: 2018,
  },
  'Gundam Build Divers Re:RISE': {
    id: 'build-divers-rerise',
    title_zh: '高达创战潜者Re:RISE',
    title_jp: 'ガンダムビルドダイバーズRe:RISE',
    era: 'BF',
    year_aired: 2019,
  },
  'Gundam Breaker Battlogue': {
    id: 'breaker-battlogue',
    title_zh: '高达 破坏者 BATTLOGUE',
    title_jp: 'ガンダムブレイカー バトローグ',
    era: 'BF',
    year_aired: 2021,
  },
  'Gundam Build Metaverse': {
    id: 'build-metaverse',
    title_zh: '高达创战元宇宙',
    title_jp: 'ガンダムビルドメタバース',
    era: 'BF',
    year_aired: 2023,
  },
}

export function lookupWork(rawSeries: string | undefined): Work | undefined {
  if (!rawSeries) return undefined
  const normalized = rawSeries.trim()
  if (WORKS_SEED[normalized]) return WORKS_SEED[normalized]
  const withoutPrefix = normalized.replace(/^Mobile Suit\s+/i, '')
  for (const [key, work] of Object.entries(WORKS_SEED)) {
    if (key.replace(/^Mobile Suit\s+/i, '') === withoutPrefix) return work
  }
  return undefined
}
